### ISSUE TITLE
Fix CNDB GH Action for updating Stargate version (`stargate-update-version.yaml`)

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/data-api#1400]
When a new Stargate version (v2.0 only for now) gets published, a Github `repository_dispatch` event is sent to CNDB, to update `pom.xml` to use newly released Stargate version.

This used to be done both for Stargate v2.0 and v2.1 publish workflows, but due to CNDB changes to active branches, it only works for v2.0 currently. GH Action is defined in:

https://github.com/riptano/cndb/actions/workflows/stargate-update-version.yaml

We should fix things to work on Stargate v2.1 as well, but since things are in-flux wrt CNDB branches/versions, we may want to wait for a bit and do this only after things settle.

FWTW currently CNDB has mapping so that:

* `main` (renamed from `vsearch`; CNDB 0.2.0-SNAPSHOT) uses Stargate v2.1.x
*  `legacy-cndb-with-dse` (renamed from `master`, CNDB 0.1.0-SNAPSHOT)  uses Stargate v2.0.x 

and GH action has:

```
on:
  repository_dispatch:
    types: [ c2-v2-release ]
    # ....
      - name: Create pull-request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Use Stargate ${{ steps.update.outputs.version }}
          branch: update-stargate-version
          branch-suffix: short-commit-hash
          base: master
```

meaning:

* Workflow is started on Stargate v2.0 release (and uses 2.0.x version)
* PR is created against `master`, which seems to be translates into `legacy-cndb-with-dse` by action.
