### ISSUE TITLE
Enable HTTP request log (access log) in Production

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/data-api#1498]
Although #752 was completed months ago, it doesn't look like HTTP request logs are enabled in Production kubes. This is probably because `src/main/resources/application.yaml` has:

```
quarkus:
  http:
    # access log format, must be explicitly enabled
    access-log:
      pattern: "%h %l %t \"%r\" %s %b"

```

and does not have `enabled: true` (which as per https://quarkus.io/guides/http-reference#configuring-http-access-logs is needed, as property [quarkus.http.access-log.enabled](https://quarkus.io/guides/http-reference#quarkus-vertx-http_quarkus-http-access-log_quarkus-http-access-log-enabled).
And we do not (I think, given there are no entries in Splunk) have matching ENV override (`QUARKUS_HTTP_ACCESS_LOG_ENABLED `) either.

There are at least 2 ways we could do this:

1. Enable in `application.yaml` for all envs (although could also disable for tests, via `src/test/resources/application.yaml` to reduce noise)
2. Enable via deployment (Helm Chart) by ENV `QUARKUS_HTTP_ACCESS_LOG_ENABLED`.

Unless there are specific reasons not to, I am leaning towards (1).
