### ISSUE TITLE
Pass the API Authentication token through to Embedding Providers if no other auth available

### ISSUE THREAD

**Issue by amorton** [stargate/data-api#2099]
We do something like this already for the RerankingProvider, so we can look as `NvidiaRerankingProvider` for prior art.

We can tweak it a little for the embedding.

The embedding providers have config like such in `embedding-providers-config.yaml` :  

```
        nvidia:
          # see https://docs.api.nvidia.com/nim/reference/nvidia-embedding-2b-infer
          display-name: Nvidia
          enabled: true
          url: https://ai.api.nvidia.com/v1/retrieval/nvidia/embeddings
          supported-authentications:
            NONE:
              enabled: true
          properties:
            max-batch-size: 8
          models:
            - name: NV-Embed-QA
              vector-dimension: 1024
              properties:
                max-tokens: 512
```

We want some sort of positive config setting that needs to be set, to avoid sending any auth info without explicit config. 

So, lets add to the properties for the NONE auth config (similar to how there are settings for the `HEADER`) mode. Add a property called something like `auth-token-passthrough` that if true we will do the pass through as the `Authorization` header.
